framework:
    messenger:
        failure_transport: failed

        transports:
            # Async transport for most messages
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            
            # Transport for failed messages
            failed: 'doctrine://default?queue_name=failed'

            # Sync transport specifically for mailer
            sync_mailer: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Route mailer messages to the sync_mailer transport
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync_mailer

            # Route chat and SMS messages to async transport
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Your custom messages can still go to async if needed
            # 'Kibuzn\Message\YourMessage': async
